name: Build SunamoYouTube

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoYouTube
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoYouTube/SunamoYouTube.csproj

    - name: Build
      run: dotnet build SunamoYouTube/SunamoYouTube.csproj --configuration Release --no-restore

  test:
    name: Test SunamoYouTube.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoYouTube.Tests/SunamoYouTube.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoYouTube.Tests/SunamoYouTube.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoYouTube.Tests/SunamoYouTube.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
